### ISSUE TITLE
Unresolved reference with Ktor 3.0.0-beta-1

### ISSUE THREAD

**Issue by Savrov** [chopyourbrain/kontrol#5]
Hello, thank you for a lib, it potentially can save us some time at kmp project, but we have got into a trouble here. We are required to use Ktor version 3.0.0-beta-1 because of SSE functionality, but eventually there is a problem with ResponseObserver - it's marked as unresolved.

<img width="1324" alt="image" src="https://github.com/chopyourbrain/kontrol/assets/5410076/9aa2bc23-9561-4235-b0b2-76c23148e2d6">

When I try to import it - nothing happens. 

There is a difference in how ResponseObserver is defined in Ktor 2.3.6 and in 3.0.0-beta-1
2.3.6:
<img width="1039" alt="image" src="https://github.com/chopyourbrain/kontrol/assets/5410076/3c6a8891-4f12-498f-9eb1-a97b24939df3">

3.0.0-beta-1:
<img width="979" alt="image" src="https://github.com/chopyourbrain/kontrol/assets/5410076/6827e71a-afa4-4683-936b-d3460f7b25f4">

Is it possible to release a library with support of 3.0.0-beta-1?

**Comment by Savrov** [comment]
I wanted to make a PR, but access to this repo was denied. Anyway, fix can be easy as:


`ResponseObserver.prepare { onResponse(observer) }.install(scope)`


<img width="1256" alt="image" src="https://github.com/chopyourbrain/kontrol/assets/5410076/ceee94d1-a5fe-48f7-90d0-05e2119667f4">

**Comment by chopyourbrain** [comment]
@Savrov I hope, that you still need this update. Changes are in 0.1.3 version
